// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGd3_bVUSx6C9Gp0-wyjfOmj5WzTLbv9U',
    appId: '1:886449196259:web:56a1f0e39b3464069689d6',
    messagingSenderId: '886449196259',
    projectId: 'fir-second-project-b6cd4',
    authDomain: 'fir-second-project-b6cd4.firebaseapp.com',
    storageBucket: 'fir-second-project-b6cd4.appspot.com',
    measurementId: 'G-CG4MF65QX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2lgKFU5ltF9HYDWYhhvke-PxuQpU8eQ',
    appId: '1:886449196259:android:dfe3aa2e76fede3d9689d6',
    messagingSenderId: '886449196259',
    projectId: 'fir-second-project-b6cd4',
    storageBucket: 'fir-second-project-b6cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5Asl0-ht02KKoBYW0aBiJapOWrurQ_4',
    appId: '1:886449196259:ios:269ade68479a0d119689d6',
    messagingSenderId: '886449196259',
    projectId: 'fir-second-project-b6cd4',
    storageBucket: 'fir-second-project-b6cd4.appspot.com',
    iosBundleId: 'com.example.chatAppFlutterThree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5Asl0-ht02KKoBYW0aBiJapOWrurQ_4',
    appId: '1:886449196259:ios:1c39ec1c2a6df9519689d6',
    messagingSenderId: '886449196259',
    projectId: 'fir-second-project-b6cd4',
    storageBucket: 'fir-second-project-b6cd4.appspot.com',
    iosBundleId: 'com.example.chatAppFlutterThree.RunnerTests',
  );
}
